name: Sync commits with individual packages

on:
  push:
    branches:
      - '*'
    paths:
      - packages/**
    tags-ignore:
      - '*'
  create:
    tags:
        - '*'
  delete:
    tags:
        - '*'

jobs:
  sync_commits:
    runs-on: ubuntu-latest
    name: Sync Commits
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: frankdejonge/use-github-token@1.0.2
        with:
          authentication: 'username:${{ secrets.PERSONAL_GITHUB_TOKEN }}'
          user_name: 'Programic Bot'
          user_email: 'development@programic.com'
      - name: Cache splitsh
        uses: actions/cache@v4
        with:
          path: './splitsh'
          key: '${{ runner.os }}-splitsh-v101'
      - name: Subtree split
        uses: acrobat/subtree-splitter@v1.1.5
        with:
          config-path: .github/subtree-splitter.json

